# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1j_g4sod2CU8L0r57J6STsm6EYxu32eZ8
"""

import streamlit as st
import pandas as pd
import joblib
from sklearn.metrics import *

st.set_page_config(page_title="Credit Default Prediction")

st.title("Credit Card Default Prediction App")

uploaded_file = st.file_uploader("Upload Test CSV File", type=["csv"])

model_options = [
    "Logistic Regression",
    "Decision Tree",
    "KNN",
    "Naive Bayes",
    "Random Forest",
    "XGBoost"
]

selected_model = st.selectbox("Select Model", model_options)

if uploaded_file is not None:

    input_data = pd.read_csv(uploaded_file)

    if "credit_default" not in input_data.columns:
        st.error("CSV must contain 'credit_default' column")
    else:
        X_input = input_data.drop("credit_default", axis=1)
        y_true = input_data["credit_default"]

        model_paths = {
            "Logistic Regression": "saved_models/logistic.pkl",
            "Decision Tree": "saved_models/tree.pkl",
            "KNN": "saved_models/knn.pkl",
            "Naive Bayes": "saved_models/bayes.pkl",
            "Random Forest": "saved_models/forest.pkl",
            "XGBoost": "saved_models/xgboost.pkl"
        }

        model = joblib.load(model_paths[selected_model])
        scaler = joblib.load("saved_models/scaler.pkl")

        if selected_model in ["Logistic Regression", "KNN"]:
            X_input = scaler.transform(X_input)

        predictions = model.predict(X_input)

        st.subheader("Evaluation Metrics")
        st.write("Accuracy:", accuracy_score(y_true, predictions))
        st.write("Precision:", precision_score(y_true, predictions))
        st.write("Recall:", recall_score(y_true, predictions))
        st.write("F1 Score:", f1_score(y_true, predictions))
        st.write("MCC:", matthews_corrcoef(y_true, predictions))

        if hasattr(model, "predict_proba"):
            probs = model.predict_proba(X_input)[:, 1]
            st.write("AUC:", roc_auc_score(y_true, probs))

        st.subheader("Confusion Matrix")
        st.write(confusion_matrix(y_true, predictions))

        st.subheader("Classification Report")
        st.text(classification_report(y_true, predictions))